### ISSUE TITLE
Can't send comments data in Pseudocode

### ISSUE THREAD

**Issue by Kira-cxy** [IDAConnect/IDAConnect#6]
I test the comments in disassembly mode, it works fine.
When I try add some comments in Pseudocode mode, the error is shown.
On Windows 10
```
Traceback (most recent call last):
  File "Z:/tools/IDA/IDA_Pro_v7.0_Portable/plugins\idaconnect\core\hooks.py", line 446, in _hxe_callback
    self._send_user_cmts(func.startEA)
  File "Z:/tools/IDA/IDA_Pro_v7.0_Portable/plugins\idaconnect\core\hooks.py", line 488, in _send_user_cmts
    cmts = HexRaysHooks._get_user_cmts(ea)
  File "Z:/tools/IDA/IDA_Pro_v7.0_Portable/plugins\idaconnect\core\hooks.py", line 482, in _get_user_cmts
    cmts.append(((tl.ea, tl.itp), Event.decode(cmt)))
  File "Z:/tools/IDA/IDA_Pro_v7.0_Portable/plugins\idaconnect\core\events.py", line 54, in decode
    return s.decode(locale.getpreferredencoding())
AttributeError: 'citem_cmt_t' object has no attribute 'decode'
IDAPython: Hex-rays python callback returned non-integer; value ignored.
```

On OS X 10.13.4
```
Traceback (most recent call last):
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/idaconnect/core/hooks.py", line 446, in _hxe_callback
    self._send_user_cmts(func.startEA)
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/idaconnect/core/hooks.py", line 488, in _send_user_cmts
    cmts = HexRaysHooks._get_user_cmts(ea)
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/idaconnect/core/hooks.py", line 482, in _get_user_cmts
    cmts.append(((tl.ea, tl.itp), Event.decode(cmt)))
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/idaconnect/core/events.py", line 55, in decode
    return s.decode('utf-8')
AttributeError: 'citem_cmt_t' object has no attribute 'decode'
IDAPython: Hex-rays python callback returned non-integer; value ignored.
```

**Comment by NeatMonster** [comment]
Should be fixed by commit 844be5c9ce03bdb758e11a2d9d6694b6be6af693 (not retro-compatible). I'm sure there are a lot more issues related to synchronizing Hex-Rays, so don't hesitate to reopen this issue if you encounter another one.
